version: '3.8'

services:
  # PostgreSQL database
  toneshift-postgres:
    image: postgres:15
    container_name: toneshift-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=toneshift
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - toneshift-network

  # Backend API service
  toneshift-backend:
    build: ./toneshift-backend
    container_name: toneshift-backend
    restart: always
    depends_on:
      - toneshift-postgres
      - ollama
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=toneshift-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=toneshift
      - JWT_SECRET=toneshift_secret_key
      - OLLAMA_API_URL=http://ollama:11434/api
      - OLLAMA_MODEL=gemma3:4b
    networks:
      - toneshift-network

  # Frontend service
  toneshift-frontend:
    build: ./toneshift-frontend
    container_name: toneshift-frontend
    restart: always
    depends_on:
      - toneshift-backend
    ports:
      - "19006:19006"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api  # For browser access
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    networks:
      - toneshift-network
      
  # Ollama service for AI model serving
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - toneshift-network

networks:
  toneshift-network:
    driver: bridge

volumes:
  postgres-data:
  ollama-data: